name: Maven CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main 

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Java JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'

      - name: Build with Maven
        run: mvn compile

  test:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Java JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'

      - name: Run tests with Maven
        run: mvn test

  package:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Java JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11' 

      - name: Package with Maven
        run: mvn package

  deploy:
    runs-on: ubuntu-latest
    needs: package
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Java JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11' 

      - name: Deploy with Maven
        run: mvn deploy
